# Generated by Django 5.2.4 on 2025-07-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='stats',
            field=models.JSONField(),
        ),
    ]
