# Generated by Django 5.2.4 on 2025-08-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_filescan_scanpolicy_collaborationpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='FileScan',
        ),
        migrations.DeleteModel(
            name='ScanPolicy',
        ),
        migrations.RenameField(
            model_name='scanlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='collaborationmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='extensions',
            field=models.CharField(default='.exe,.dll,.pdf,.txt,.docx,.eml', max_length=255),
        ),
        migrations.AddField(
            model_name='policy',
            name='keywords',
            field=models.TextField(default='order\ndocument\nurgent\nlogin\npassword\naccount\nfree\noffer\ndiscount'),
        ),
        migrations.AddField(
            model_name='policy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CollaborationPost',
        ),
    ]
