# Generated by Django 5.0.14 on 2025-08-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_collaborationmessage_id_alter_policy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='stats',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='scanlog',
            table='app_scanlog',
        ),
    ]
