from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('account/', views.account_view, name='account'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('file-integrity-checker/', views.file_integrity_checker, name='file_integrity_checker'),
    path('upload/', views.upload_files, name='upload_files'),
    path('collaboration/', views.collaboration, name='collaboration'),
    path('policies/', views.policies, name='policies'),
    path('edit-message/<int:message_id>/', views.edit_message, name='edit_message'),
    path('delete-message/<int:message_id>/', views.delete_message, name='delete_message'),
    path('email-analyzer/', views.email_analyzer, name='email_analyzer'),
    path('scan-single-email/', views.scan_single_email, name='scan_single_email'),
    path('scan-batch-emails/', views.scan_batch_emails, name='scan_batch_emails'),
    path('download-report/', views.download_report, name='download_report'),
    path('website-checker/', views.website_checker, name='website_checker'),
    path('check-availability/', views.check_availability, name='check_availability'),
    path('homepage-test/', views.homepage_test, name='homepage_test'),
    path('ping-test/', views.ping_test, name='ping_test'),
    path('traceroute-test/', views.traceroute_test, name='traceroute_test'),
    path('dns-check/', views.dns_check, name='dns_check'),
    path('get_logs/', views.get_logs, name='get_logs'),
    path('get_collaboration/', views.get_collaboration, name='get_collaboration'),
    path('get_policies/', views.get_policies, name='get_policies'),
    path('download-logs/', views.download_logs, name='download_logs'),
    path('download-website-results/', views.download_website_results, name='download_website_results'),
]